blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Questions & Discussions
    url: https://github.com/griggen/chaptercheck/discussions
    about: Ask questions and discuss ideas in GitHub Discussions
